lendguru/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.http import HttpResponse
import core.views

urlpatterns = [
	url(r'^$', core.views.renderCore, name='index'),
	url(r'^admin/', admin.site.urls),
	url(r'^form/', core.views.renderResults, name='results'),
	url(r'^articles/(?P<id>[0-9]{4})/$', core.views.renderArticle, name='article_view'),
	url(r'^all_articles/$', core.views.renderArticles, name='articles_view'),
	url(r'^contact/', core.views.renderContact, name='contact'),
	url(r'^sumbitmessage/', core.views.renderSumbitMessage, name='sumbitmessage'),
	url(r'^blog/', core.views.renderBlog, name='blog'),
	url(r'^downloads/', core.views.renderDownloads, name='downloads'),
	url(r'^about/', core.views.renderAbout, name='about'),
	url(r'^newsletter/', core.views.renderNewsletter, name='newsletter'),
	url(r'^metisflow/', core.views.renderMetis, name='metis')
]

core/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import ModelForm
from .models import formData
from .models import contactData
from .models import newsletterData
from .models import metisUser

class Form(ModelForm):
	class Meta:
		model = formData
		fields = '__all__'
	amount = forms.IntegerField(label='Kwota finansowania (PLN)')
	duration = forms.IntegerField(label='Okres finansowania (mies.)')
	purpose = forms.ChoiceField(choices=(('LKO', 'Linia kredytowa odnawialna'),('KO', 'Kredyt obrotowy'),('KI', 'Kredyt inwestycyjny'),('ZST', 'Zakup środkow trwałych'),('ZN','Zakup nieruchomości'),('ALL','Wszystkie'), ('INNE','Inne (opisz poniżej)')), label='Cel finansowania',)
	time_operating = forms.IntegerField(label='Czas działalności firmy (mies.)')
	tellmore = forms.CharField(widget=forms.Textarea(attrs={'cols': 60, 'rows': 5}), required=False, label='Powiedz nam coś więcej o potrzebach finansowych Twojej firmy (nieobowiązkowe)',max_length=300)
	legal_type = forms.ChoiceField(choices=(('ZOO', 'sp. z.o.o.'),('SCYW', 'Spółka cywilna'),('SAKC', 'Spółka akcyjna'), ('INNY','Inny')), label='Rodzaj firmy',)
	email = forms.CharField(label='Adres E-Mail', max_length=30)

class ContactForm(ModelForm):
	class Meta:
		model = contactData
		fields = '__all__'
	name = forms.CharField(max_length=100)
	email = forms.CharField(max_length=30)
	phone = forms.CharField(max_length=15)
	title = forms.CharField(max_length=100)
	message = forms.CharField()

class NewsletterForm(ModelForm):
	class Meta:
		model = newsletterData
		fields = '__all__'
	email = forms.CharField(max_length=50)

class metisForm(ModelForm):
	class Meta:
		model = metisUser
		fields = '__all__'
	email = forms.CharField(max_length=50)

templates/about.html
{% extends "index_base.html" %}
{% load static %}

{% block title %}
<title>Lendguru.pl | O nas</title>
{% endblock %}

{% block body %}
<section class="main-container">

				<div class="container">
					<div class="row">

						<!-- main start -->
						<!-- ================ -->
						<div class="main col-md-8">
							<!-- page-title start -->
							<!-- ================ -->
							<h1 class="page-title">O nas</h1>
							<div class="separator-2"></div>
							<h3>Kim jesteśmy?</h3>
							<p>Jesteśmy grupą przedsiębiorców z doświadczeniem w małych firmach, przedsiębiorczości, finansach i sztucznej inteligencji, którzy mieszkali i pracowali m.in. w Stanach Zjednoczonych i Szwajcarii.</p>
							<p>W małych firmach rodzinnych zdaliśmy sobie sprawę, jak trudno jest zarządzać finansami małych firm i znaleźć właściwe finansowanie. Gdzie szukać dostawców usług finansowych? Które produkty? Jak porównać oferty?</p>
							<p>Kiedy się spotkaliśmy, zdaliśmy sobie sprawę, że mamy to co potrzeba, aby pomóc małym przedsiębiorstwom uzyskać  najlepszy możliwy dostęp do finansowania. Wiemy jak działają produkty finansowe, wiemy jakie są najtrudniejsze problemy małych firm i znamy właściwą technologię. A przede wszystkim wszyscy mamy wspólną pasję pomagania małym przedsiębiorstwom, które stanowią trzon polskiej  gospodarki, 98% wszystkich firm, gwarantując ponad 70% wszystkich miejsc pracy.</p>
							<br>
							<h3>Jaka jest nasza misja?</h3>
							<p>Naszą misją jest pomoc małym firmom w uzyskaniu właściwego finansowania. Wierzymy w silną firmę i długoterminowe podejście do wszystkiego, co robimy.</p>
							<br>
							<h3>Z jakiej technologii korzysta Lendguru?</h3>
							<p>Posiadamy obszerną bazę danych o produktach i instytucjach finansowych w Polsce, z szeroką specyfikacją każdego oferowanego produktu i własnym algorytmem Sztucznej Inteligencji, który wybiera tylko najlepsze opcje finansowania. Algorytm odczytuje potrzeby finansowe firmy i przeszukuje bazę danych w poszukiwaniu opcji, która najlepiej nadaje się do konkretnej sytuacji każdej firmy.</p>
							<p>Nasi inżynierowie i naukowcy nieustannie poprawiają Lendguru, aby zapewnić małym firmom najlepsze możliwe dopasowanie, w szybki, łatwy i bezstronny sposób.</p>
							<br>
							<h3>Jestem instytucją finansową i chcę nawiązać kontakt z Lendguru, jak mogę się z wami skontaktować?</h3>
							<p>Skontaktuj się z nami pod adresem <a href="mailto:kontakt@lendguru.pl">kontakt@lendguru.pl</a> wraz z ofertą Twoich produktów, a my wkrótce odezwiemy się do Ciebie. Cieszymy się, że możemy zaoferować naszym klientom coraz więcej coraz lepszych opcji finansowania.</p>
							<br>
							<h3>Jestem profesjonalistą i chcę zaoferować wasze usługi swoim klientom. Jak mogę to zrobić?</h3>
							<p>Napisz do nas na adres <a href="mailto:kontakt@lendguru.pl">kontakt@lendguru.pl</a> i powiedz nam o potrzebach Twoich klientów. Przedstawimy Ci nasze program współpracy z partnerami, w którym możesz oferować rozwiązania finansowe swoim klientom, wykorzystując naszą technologię i bazę danych.</p>
							<br><hr>
							<a target="_blank" href="https://www.facebook.com/lendguru" class="btn btn-lg btn-animated facebook">Facebook<i class="pl-10 fa fa-facebook-square"></i></a>
							<a target="_blank" href="https://twitter.com/lendguru" class="btn btn-lg btn-animated twitter">Twitter<i class="pl-10 fa fa-twitter"></i></a>
						</div>
						<!-- main end -->
						<aside class="col-md-4 col-lg-3 col-lg-offset-1">
							<div class="sidebar">
								<div class="block clearfix">
									<h3 class="title">Kontakt</h3>
									<div class="separator-2"></div>
									<ul class="list">
										<li><i class="fa fa-phone pr-10"></i>+48 530 154 838</li>
										<li><i class="fa fa-envelope pr-10"></i><a href="mailto:kontakt@lendguru.pl">kontakt@lendguru.pl</a></li>
									</ul>
								</div>
							</div>
						</aside>

					</div>
				</div>
			</section>

{% endblock %}

templates/contact.html
{% extends "index_base.html" %}
{% load static %}

{% block title %}
<title>Lendguru.pl | Kontakt</title>
{% endblock %}

{% block body %}
<section class="main-container">

				<div class="container">
					<div class="row">

						<!-- main start -->
						<!-- ================ -->
						<div class="main col-md-8">
							<!-- page-title start -->
							<!-- ================ -->
							<h1 class="page-title">Skontaktuj się z nami</h1>
							<div class="separator-2"></div>
							<!-- page-title end -->
							<p>Oferujemy Państwu możliwość skontaktowania się z nami za pomocą numeru telefonu, wiadomości e-mail lub poniższego formularza. Postaramy sie odpowiedzieć na Państwa pytania jak najszybciej.</p>
							<div class="alert alert-success hidden" id="MessageSent">
								Wiadomość została wysłana. Niedługo się z Państwem skontaktujemy!
							</div>
							<div class="alert alert-danger hidden" id="MessageNotSent">
								Coś poszło nie tak. Sugerujemy odświeżyć stronę i spróbować ponownie.
							</div>
							<div class="contact-form">
								<form class="form" action="/sumbitmessage/" method="post" accept-charset="utf-8">
									{% csrf_token %}
									<div class="form-group has-feedback">
										<label for="name">Imię i nazwisko / Nazwa firmy*</label>
										<input type="text" class="form-control" id="id_name" name="name" placeholder="" required>
										<i class="fa fa-user form-control-feedback"></i>
									</div>
									<div class="form-group has-feedback">
										<label for="email">E-Mail*</label>
										<input type="email" class="form-control" id="id_email" name="email" placeholder="" required>
										<i class="fa fa-envelope form-control-feedback"></i>
									</div>
									<div class="form-group has-feedback">
										<label for="subject">Temat wiadomości*</label>
										<input type="text" class="form-control" id="id_title" name="title" placeholder="" required>
										<i class="fa fa-navicon form-control-feedback"></i>
									</div>
									<div class="form-group has-feedback">
										<label for="subject">Numer telefonu</label>
										<input type="text" class="form-control" id="id_phone" name="phone" placeholder="">
										<i class="fa fa-phone form-control-feedback"></i>
									</div>
									<div class="form-group has-feedback">
										<label for="message">Treść wiadomości*</label>
										<textarea class="form-control" rows="6" id="id_message" name="message" placeholder="" required></textarea>
										<i class="fa fa-pencil form-control-feedback"></i>
									</div>
									<button type="submit" class="save btn btn-animated btn-default-transparent">Wyślij<i class="fa fa-arrow-right"></i></button>
								</form>
							</div>
						</div>
						<!-- main end -->

						<!-- sidebar start -->
						<!-- ================ -->
						<aside class="col-md-4 col-lg-3 col-lg-offset-1">
							<div class="sidebar">
								<div class="block clearfix">
									<h3 class="title">Kontakt</h3>
									<div class="separator-2"></div>
									<ul class="list">
										<li><i class="fa fa-phone pr-10"></i>+48 530 154 838</li>
										<li><i class="fa fa-envelope pr-10"></i><a href="mailto:kontakt@lendguru.pl">kontakt@lendguru.pl</a></li>
									</ul>
								</div>
							</div>
						</aside>
						<!-- sidebar end -->

					</div>
				</div>
			</section>

{% endblock %}

templates/index.html
{% extends "index_base.html" %}
{% load static %}

{% block body %}

<div class="main-container parallax jumbotron border-clear translucent-bg margin-clear" style="min-height: 75vh; background-position: 50%; padding-left:20px; background-attachment: fixed; background-size: cover; background-image:url(&#39;{% static "gfx/man-worker.jpg" %}&#39;);">
	<!-- section start -->
	<!-- ================ -->

	<div class="container">
			<br><br>
			<span style="display: inline-block; vertical-align: middle; line-height: normal;">
				<h1 class="tp-caption xlarge_white" style="color: white">Lendguru</h1>
			</span>
	</div>
</div>

<section class="section pv-40 dark-bg clearfix">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="call-to-action">
					<div class="row">
						<div class="col-sm-8">
							<h3 class="mt-10 text-muted">Znajdź opcje finansowania Twojego biznesu</h3>
						</div>
						<div class="col-sm-4 text-right">
							<a href="#formularz" class="btn btn-lg btn-default btn-animated">Wypełnij formularz<i class="fa fa-arrow-right pl-20"></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="section light-gray-bg">
	<div class="container">
		<div class="col-md-6">
			<img style="width: 700px" src="{% static "gfx/man-pc.jpg"%}" alt="">
		</div>
		<div class="col-md-6">
			<p class="lead" style="font-size: 2em; padding-left:20px">Wiele opcji finansowania Twojego biznesu</p>
			<ul class="list" style="font-size: 1.5em; padding-left:40px">
				<li class="medium"><i class="icon-check text-default"></i> Linie kredytowe</li>
				<li class="medium"><i class="icon-check text-default"></i> Kredyty inwestycyjne</li>
				<li class="medium"><i class="icon-check text-default"></i> Faktoring</li>
				<li class="medium"><i class="icon-check text-default"></i> Leasing</li>
				<li class="medium"><i class="icon-check text-default"></i> Finansowanie nieruchomości</li>
				<li class="medium"><i class="icon-check text-default"></i> Pożyczki pozabankowe</li>
			</ul>
		</div>
	</div>
</section>

<section class="section">
	<div class="container">
		<div class="col-md-6">
			<div class="feature-box-2 margin-clear">
				<br class="hidden-sm hidden-xs"><br class="hidden-sm hidden-xs"><br class="hidden-sm hidden-xs">
				<p >Wiemy jak trudno jest małym i średnim firmom znaleźć, porównać i uzyskać najkorzystniejsze opcje finansowania.
					Proces jest długotrwały, a porównanie ofert okazuje się skomplikowane.W Lendguru.pl chcemy to uprościć. Ty wypełniasz jeden prosty formularz, a my za Ciebie wybieramy i porównujemy
					kilkadziesiąt ofert finansowania Twojego biznesu dostępnych na rynku i prezentujemy je w przystępnej formie.</p>
					<br/>
					<h4>Korzystasz z naszej platformy za darmo!
						... i nie masz obowiązku wyboru żadnej z zaprezentowanych ofert!</h4>
					</div>
				</div>
				<div class="col-md-6">
					<img style="width: 700px" src="{% static "gfx/bkg.jpg"%}" alt="">
				</div>
			</div>
		</section>

		<section class="section light-gray-bg">
			<div class="container">
				<div class="col-md-6">
					<img style="width: 700px" src="{% static "gfx/man-desktop.jpg"%}" alt="">
				</div>
				<div class="col-md-6">
					<br class="hidden-sm hidden-xs">
					<div class="feature-box-2 margin-clear">
						<span class="icon without-bg"><i class="text-default icon-snow"></i></span>
						<div class="body">
							<h4>Prosto, szybko, bez żadnych kosztów</h4>
							<p>Zbieramy i selekcjonujemy dla Ciebie tylko najlepsze oferty na rynku, które są dopasowane do Twojego biznesu.</p>
							<div class="separator-2 visible-lg"></div>
						</div>
					</div>
					<div class="feature-box-2 margin-clear">
						<span class="icon without-bg"><i class="text-default icon-tools"></i></span>
						<div class="body">
							<h4>Twoja decyzja</h4>
							<p>Ostateczną decyzję zawsze pozostawiamy Tobie - to Ty najlepiej znasz swój biznes.</p>
							<div class="separator-2 visible-lg"></div>
						</div>
					</div>
					<div class="feature-box-2 margin-clear">
						<span class="icon without-bg"><i class="text-default icon-star-empty"></i></span>
						<div class="body">
							<h4>Pełen profesjonalizm</h4>
							<p>Jesteśmy ekspertami w dziedzinie finansów przedsiębiorstw, pracowaliśmy w najlepszych instytucjach finansowych z różnorodnymi produktami finansowymi.</p>
						</div>
					</div>
				</div>
			</div>
		</section>

		<section class="section default-bg" >
			<div class="container">
				<div class="col-md-6">
					<br class="hidden-sm hidden-xs">
					<div class="feature-box-2 margin-clear">
						<span class="icon without-bg">1.</span>
						<div class="body">
							<h4>Wypełnij formularz</h4>
							<p>Wpisz obok dane swojej firmy. Jeśli chcesz, możesz powiedzieć nam o swoich dodatkowych uwagach, a my to uwzględnimy.</p>
							<div class="separator-2 visible-lg"></div>
						</div>
					</div>
					<div class="feature-box-2 margin-clear">
						<span class="icon without-bg">2.</span>
						<div class="body">
							<h4>Nasz system wybierze najlepsze propozycje dla Ciebie</h4>
							<p>Zostanie Ci przedstawiona lista najbardziej korzystnych ofert dla Ciebie w odpowiedniej kolejności.</p>
							<div class="separator-2 visible-lg"></div>
						</div>
					</div>
					<div class="feature-box-2 margin-clear">
						<span class="icon without-bg">3.</span>
						<div class="body">
							<h4>Otrzymasz wiadomość od naszej firmy.</h4>
							<p>Postaramy się jak najszybciej z Tobą skontaktować.</p>
						</div>
					</div>
				</div>

				<div class="col-md-6 body">
					<div id="formularz">
						<form class="form-inline" action="/form/" method="post" accept-charset="utf-8">
							{% csrf_token %}

							<div class="row">
								<div class="col-md-6">
									{{ form.amount.label }}
									<span data-toggle="tooltip" class="glyphicon glyphicon-question-sign" style="color: rgba(70, 70, 70, 0.5)" aria-hidden="true" title="Podaj kwotę finansowania."></span>
									<br/>
									<div class="input-group input-group" style="width:100%; padding-bottom: 10px">
										<div class="input-group-addon" style="color:white">PLN</div>
										<input class="form-control" type="number" name="amount" id="id_amount" step="1000" min="0" required/>
									</div>
									<br/>

									{{ form.duration.label }}
									<span data-toggle="tooltip" class="glyphicon glyphicon-question-sign" style="color: rgba(70, 70, 70, 0.5)" aria-hidden="true" title="Podaj okres finansowania."></span>
									<br/>
									<div class="input-group input-group" style="width:100%; padding-bottom: 10px">
										<div class="input-group-addon" style="color:white"><span class="glyphicon glyphicon-time" aria-hidden="true"></span></div>
										<input class="form-control" type="number" name="duration" id="id_duration" min="0" required>
									</div>
									<br/>

									{{ form.time_operating.label }}
									<span data-toggle="tooltip" class="glyphicon glyphicon-question-sign" style="color: rgba(70, 70, 70, 0.5)" aria-hidden="true" title="toottip text here..."></span>
									<br/>
									<div class="input-group input-group" style="width:100%; padding-bottom: 10px">
										<div class="input-group-addon" style="color:white"><span class="glyphicon glyphicon-time" aria-hidden="true"></span></div>
										<input class="form-control" type="number" name="time_operating" id="id_time_operating" min="0" required>
									</div>
									<br/>
								</div>
								<div class="col-md-6">

									{{ form.legal_type.label }}
									<span data-toggle="tooltip" class="glyphicon glyphicon-question-sign" style="color: rgba(70, 70, 70, 0.5)" aria-hidden="true" title="toottip text here..."></span>
									<br/>
									<div style="padding-bottom: 10px">
									<select class="form-control" name="legal_type" id="id_legal_type" style="width: 100%">
										{% for choice in form.legal_type.field.choices %}
										<option style="color:black;" value="{{ choice|first }}">{{ choice|last }}</option>
										{% endfor %}
									</select>
									<br/>
									</div>


									{{ form.email.label }}
									<span data-toggle="tooltip" class="glyphicon glyphicon-question-sign" style="color: rgba(70, 70, 70, 0.5)" aria-hidden="true" title="toottip text here..."></span>
									<br/>
									<div class="input-group input-group" style="width:100%; padding-bottom: 10px">
										<div class="input-group-addon" style="color:white">@</div>
										<input class="form-control" type="email" name="email" id="id_email" required>
									</div>
									<br/>

									{{ form.purpose.label }}
									<span data-toggle="tooltip" class="glyphicon glyphicon-question-sign" style="color: rgba(70, 70, 70, 0.5)" aria-hidden="true" title="toottip text here..."></span>
									<br/>
									<select class="form-control" name="purpose" id="id_purpose" style="width: 100%; padding-bottom: 10px">
										{% for choice in form.purpose.field.choices %}
										<option style="color:black;" value="{{ choice|first }}">{{ choice|last }}</option>
										{% endfor %}
									</select>
								</div>
							</div>

							<br/>
							{{ form.tellmore.label }}
							<span data-toggle="tooltip" class="glyphicon glyphicon-question-sign" aria-hidden="true" title="toottip text here..."></span>
							<br/>
							<textarea class="form-control" name="tellmore" id="id_tellmore" rows="4" style="width:100%"></textarea>
							<br/>

							<input type="checkbox" name="acceptance" required> Wyrażam zgodę na przetwarzanie moich danych osobowych</input>
							<br/>
							<button type="submit" class="save btn btn-animated btn-default-transparent" style="float: right">Wyślij<i class="fa fa-arrow-right"></i></button>
						</form>
					</div>
				</div>
			</div>
		</section>

		{% if articles|length > 0 %}
		<section class="section light-gray-bg">
			<div class="container">
				<div class="block clearfix">
					<h3 class="title">Najnowsze artykuły</h3>
					<div class="separator-2"></div>

					{% for article in articles reversed %}
					<div class="media margin-clear">
						<div class="media-body">
							<h6 class="media-heading"><a href="articles/{{ article.id|stringformat:"04d" }}">{{ article.title }}</a></h6>
							{% if article.description|length > 0 %}
							<p class="small margin-clear">{{ article.description }}</p>
							{% else %}
							{% if article.text|length > 100 %}
							<p class="small margin-clear">{{ article.text|slice:":97" }}...</p>
							{% else %}
							<p class="small margin-clear">{{ article.text }}</p>
							{% endif %}
							{% endif %}
						</div>
						<hr>
					</div>
					{% endfor %}

					<div class="text-right space-top">
						<a href="all_articles/" class="link-dark"><i class="fa fa-plus-circle pl-5 pr-5"></i>Więcej artykułów</a>
					</div>
				</div>
			</div>
		</section>
		<section class="section light-gray-bg pv-40 clearfix">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="call-to-action text-center">
							<div class="row">
								<div class="col-sm-8 col-sm-offset-2">
									<h2 class="title">Zapisz się do newslettera</h2>
									<div class="separator"></div>
									<form class="form-inline margin-clear" action="/newsletter/" method="post" accept-charset="utf-8">
										{% csrf_token %}
										<div class="input-group input-group">
											<div class="input-group-addon">@</div>
											<input class="form-control" type="email" name="email" id="id_email" placeholder="Adres E-Mail" required>
										</div>
										<button type="submit" class="btn btn-gray-transparent btn-animated margin-clear">Wyślij<i class="fa fa-send"></i></button>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		{% endif %}

		{% endblock %}

templates/metisflow.html
<head>
	{% block title %}<title>Metisflow</title>{% endblock %}

	{% load static %}
	<link rel="shortcut icon" href="{% static "template/images/favicon.ico" %}">

	<!-- Web Fonts -->
	<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Raleway:700,400,300' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=PT+Serif' rel='stylesheet' type='text/css'>

	<!-- Bootstrap core CSS -->
	<link href="{% static "template/bootstrap/css/bootstrap.css" %}" rel="stylesheet">

	<!-- Font Awesome CSS -->
	<link href="{% static "template/fonts/font-awesome/css/font-awesome.css" %}" rel="stylesheet">

	<!-- Fontello CSS -->
	<link href="{% static "template/fonts/fontello/css/fontello.css" %}" rel="stylesheet">

	<!-- Plugins -->
	<link href="{% static "template/plugins/magnific-popup/magnific-popup.css" %}" rel="stylesheet">
	<link href="{% static "template/css/animations.css" %}" rel="stylesheet">
	<link href="{% static "template/plugins/hover/hover-min.css" %}" rel="stylesheet">

	<!-- the project core CSS file -->
	<link href="{% static "template/css/style.css" %}" rel="stylesheet" >
	<link href="{% static "template/css/typography-default.css" %}" rel="stylesheet" >

	<!-- Color Scheme (In order to change the color scheme, replace the blue.css with the color scheme that you prefer)-->
	<link href="{% static "template/css/skins/light_blue.css" %}" rel="stylesheet">
	<!-- Custom css -->
	<link href="{% static "template/css/custom.css" %}" rel="stylesheet">

	<link href="{% static "cookielaw/css/cookielaw.css" %}" rel="stylesheet">
</head>

{% load static %}

<body style="background-color: #24bec3">
	<div class="col-md-6">
		<img style="max-height: 14vh" src="{% static "gfx/metiz.png"%}">
	</div>
	<div class="col-md-6" style="height: 14vh; text-align: right; color: white; font-size: 36px; line-height: 14vh;">
		<b>Your CFO at click-distance.</b>
	</div>
	{% if post %}
	<br><br><br>
	<center style="font-size: 26px">Thanks for signing up for early access invite!</center>
	{% else %}
	<div style="font-size: 36px; color: white;">
		<p class="lead" style="font-size: 36px; margin-left: 10vw;">Optimizing your finances while you expand the business.</p>
		<br><br>
	</div>
	<div class="col-md-6">
		<img style="max-height: 66vh; float: right" src="{% static "gfx/metizbkg.png"%}">
	</div>
	<div class="col-md-6" style="padding-left:40px; color: white; padding-top: 40px">
		<ul class="list lead" style="color: white">
			<li class="medium"><i class="icon-check"></i> Cashflow awareness</li>
			<li class="medium"><i class="icon-check"></i> Management benchmarks</li>
			<li class="medium"><i class="icon-check"></i> Actionable intelligence</li>
			<li class="medium"><i class="icon-check"></i> Forecast-based decision-making</li>
		</ul>
		<br><br>
		<p class="lead">Sign up for early access invite</p>
		<form class="form-inline" action="/metisflow/" method="post" accept-charset="utf-8">
			{% csrf_token %}
			<div class="input-group input-group">
				<div class="input-group-addon">@</div>
				<input class="form-control" type="email" name="email" id="id_email" required>
			</div>
			<button type="submit" class="save btn btn-animated btn-transparent" style="color: black">Send<i class="fa fa-arrow-right"></i></button>
		</form>
	</div>
	{% endif %}
</body>

templates/newsletter.html
{% extends "index_base.html" %}
{% load static %}

{% block title %}
<title>Lendguru.pl | Newsletter</title>
{% endblock %}

{% block body %}
<section class="main-container">

				<div class="container">
					<div class="row">

						<!-- main start -->
						<!-- ================ -->
						<div class="main col-md-8">
							<!-- page-title start -->
							<!-- ================ -->
							<h1 class="page-title">Zapisz się do newslettera</h1>
							<div class="separator-2"></div>
							{% if post %}
							<p>Zostałeś zapisany do newslettera!</p>
							{% else %}
							<p>Jeżeli chcesz być na bieżąco, podaj swój adres e-mail, a będziemy wysyłać do Ciebie to, Cię najbardziej interesuje.</p>
							<div id="formularz">
								<form class="form-inline" action="/newsletter/" method="post" accept-charset="utf-8">
									{% csrf_token %}
									{{ form.email.label }}
									<br/>
									<div class="input-group input-group">
										<div class="input-group-addon">@</div>
										<input class="form-control" type="email" name="email" id="id_email" required>
									</div>
									<button type="submit" class="save btn btn-animated btn-transparent">Wyślij<i class="fa fa-arrow-right"></i></button>
								</form>
								</div>
								{% endif %}
						</div>
						<!-- main end -->

					</div>
				</div>
			</section>

{% endblock %}